imports:
  - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8-all-deprecations.yml" }
  # includes:
  # - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8.0-deprecations.yml" }
  # - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8.1-deprecations.yml" }
  # - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8.2-deprecations.yml" }
  # - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8.3-deprecations.yml" }
  # - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8.4-deprecations.yml" }
  # - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8.5-deprecations.yml" }
  # - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8.6-deprecations.yml" }
  # - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8.7-deprecations.yml" }
  # - { resource: "vendor/palantirnet/drupal-rector/config/drupal-8/drupal-8.8-deprecations.yml" }

parameters:
  autoload_paths:
    - 'web/core'
    - 'web/core/modules'
    - 'web/modules'
    - 'web/profiles'

  exclude_paths:
    # This path is used by the upgrade_status module.
    - '*/upgrade_status/tests/modules/*'
    # If you would like to skip test directories, uncomment the following lines:
    # - '*/tests/*'
    # - '*/Tests/*'

  file_extensions:
    - module
    - theme
    - install
    - profile
    - inc
    - engine

  # If you would like Rector to include PHPUnit 8 upgrades, uncomment the following lines:
  # sets:
  #   - phpunit80

  # Create `use` statements.
  auto_import_names: true
  # Do not convert `\Drupal` to `Drupal`, etc.
  import_short_classes: false
  # This will not import classes used in PHP DocBlocks, like in /** @var \Some\Class */
  import_doc_blocks: false

  # This will add comments to call out edge cases in replacements.
  drupal_rector_notices_as_comments: true

services: ~
