# General ruleset for Drupal 8. Compatible with PHP 5.6 and above.
imports:
    # - { resource: "%vendor_dir%/rector/rector/config/level/coding-style/coding-style.yaml" }
    # - { resource: "%vendor_dir%/rector/rector/config/level/code-quality/code-quality.yaml" }
    # - { resource: "%vendor_dir%/rector/rector/config/level/dead-code/dead-code.yaml" }
    # - { resource: "%vendor_dir%/rector/rector/config/level/phpstan/phpstan.yaml" }

parameters:
    exclude_rectors:
        # Disabled because we may not want to use nullable comparision in
        # in all situation in Drupal 8. Ex.:
        # $user = \Drupal\user\Entity\User::load(1234);
        # -    if ($user) {
        # +    if ($user !== null) {
        - Rector\CodingStyle\Rector\If_\NullableCompareToNullRector

        # Disabled until https://github.com/rectorphp/rector/pull/1412 gets merged.
        - Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector

        # Disabled because it could not deal with the following code:
        # -use Foo\Bar\Entity\EntityInterface as FooBarEntityInterface;
        # -use Drupal\Core\Entity\EntityInterface as DrupalEntityInterface;
        # +use Foo\Bar\Entity\EntityInterface;
        # +use Drupal\Core\Entity\EntityInterface;
        # -interface EdgeEntityInterface extends FooBarEntityInterface, DrupalEntityInterface {
        # +interface EdgeEntityInterface extends EntityInterface, EntityInterface {
        - 'Rector\CodingStyle\Rector\Use_\RemoveUnusedAliasRector'

        # Disabled because it tries to remove valid parameters when a new
        # object is being created with reflection:
        # -    return $rc->newInstance($entity_type, $conjunction, $this->namespaces, $this->entityTypeManager);
        # +    return $rc->newInstance($entity_type, $this->entityTypeManager);
        - Rector\Php71\Rector\FuncCall\RemoveExtraParametersRector

        # Disabled because it was unable to parse a file.
        # [ERROR] Could not process "..." file by
        #         "Rector\Rector\AbstractRector", due to:
        #         "Node is missing "fileInfo" attribute.
        #         You probably created a new node and forgot to move attributes of old one in
        #         "Rector\CodeQuality\Rector\BinaryOp\SimplifyDeMorganBinaryRector".".
        - Rector\CodeQuality\Rector\BinaryOp\SimplifyDeMorganBinaryRector

        # Disabled because it usually generates huge one-liner conditions.
        - Rector\CodeQuality\Rector\If_\SimplifyIfElseToTernaryRector

        # Disabled because it usually suggest corrections like this that we
        # do not want apply yet:
        # -    if ($delete_route = $this->getDeleteFormRoute($entity_type)) {
        # +    if (($delete_route = $this->getDeleteFormRoute($entity_type)) !== null) {
        - Rector\CodeQuality\Rector\If_\ExplicitBoolCompareRector

        # Disabled because it failed to analyze a class:
        # [ERROR] Could not process "../Entity/ListBuilder/...ListBuilder.php"
        #         file, due to:
        #         "leaveNode() returned invalid value of type integer".
        - Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector

        # Disabled because it removes abstract methods.
        - Rector\DeadCode\Rector\ClassMethod\RemoveEmptyClassMethodRector

        # Disabled because it removes parameters from template methods:
        # -  protected function childClassMayDoSomethingHere(string $foo, string $bar, int $baz) : void {}
        # +  protected function childClassMayDoSomethingHere(): void
        # +  {
        # +  }
        - Rector\DeadCode\Rector\ClassMethod\RemoveUnusedParameterRector

        # Disabled because it was failed to analyze some files.
        # [ERROR] Could not process
        #         "../Entity/TitleProvider.php" file
        #         by "Rector\PHPStan\Rector\Assign\PHPStormVarAnnotationRector", due to:
        #         "".
        - Rector\PHPStan\Rector\Assign\PHPStormVarAnnotationRector

    Drupal8Rector\Rector\Property\PropertyToMethodCallRector:
        # Traits with properties that can be null therefore it is safer to call
        # their getter methods that ensure they do not.
        Drupal\Core\Messenger\MessengerTrait:
            messenger: messenger
        Drupal\Core\Controller\ControllerBase:
            entityTypeManager: entityTypeManager
        Drupal\Core\Entity\EntityHandlerBase:
            moduleHandler: moduleHandler
        Drupal\Core\StringTranslation\StringTranslationTrait:
            stringTranslation: getStringTranslation
        Drupal\Core\Logger\LoggerChannelTrait:
            loggerFactory: getLogger
        Drupal\Core\TypedData\TypedDataTrait:
            typedDataManager: getTypedDataManager
        Drupal\Core\Routing\RedirectDestinationTrait:
            redirectDestination: getRedirectDestination
        Drupal\Core\Routing\LocalAwareRedirectResponseTrait:
            requestContext: getRequestContext
        # Deprecated traits.
        # Drupal\Core\Routing\UrlGeneratorTrait:
        #    urlGenerator: getUrlGenerator
        # Drupal\Core\Routing\LinkGeneratorTrait
        #   linkGenerator: getLinkGenerator

services:
    Drupal8Rector\Rector\CodeStyle\DefineToConstRector: ~

    Drupal8Rector\Rector\Property\PropertyToMethodCallRector:
        arguments: ['%Drupal8Rector\Rector\Property\PropertyToMethodCallRector%']
