parameters:
    Rector\Rector\MethodCall\RenameMethodRector:
        Drupal\Core\Entity\EntityInterface:
            url: toUrl
            urlInfo: toUrl
            link: toLink
        Drupal\Core\Entity\Entity:
            # Note, you may need the "entity_field.manager" service instead of
            # entity_type.manager.
            entityManager: entityTypeManager
        Drupal\Core\Controller\ControllerBase:
            # Note, you may need the "entity_field.manager" service instead of
            # entity_type.manager.
            entityManager: entityTypeManager

    Drupal8Rector\Rector\Deprecation\ConstToClassConstFetchRector:
        AGGREGATOR_CLEAR_NEVER: Drupal\aggregator\FeedStorageInterface::CLEAR_NEVER
        COMMENT_ANONYMOUS_MAYNOT_CONTACT: Drupal\comment\CommentInterface::ANONYMOUS_MAYNOT_CONTACT
        COMMENT_ANONYMOUS_MAY_CONTACT: Drupal\comment\CommentInterface::ANONYMOUS_MAY_CONTACT
        COMMENT_ANONYMOUS_MUST_CONTACT: Drupal\comment\CommentInterface::ANONYMOUS_MUST_CONTACT
        DATETIME_DATETIME_STORAGE_FORMAT: Drupal\datetime\Plugin\Field\FieldType\DateTimeItemInterface::DATETIME_STORAGE_FORMAT
        DATETIME_DATE_STORAGE_FORMAT: Drupal\datetime\Plugin\Field\FieldType\DateTimeItemInterface::DATETIME_STORAGE_FORMAT
        DATETIME_STORAGE_TIMEZONE: Drupal\datetime\Plugin\Field\FieldType\DateTimeItemInterface::STORAGE_TIMEZONE
        DRUPAL_ANONYMOUS_RID: Drupal\user\RoleInterface::ANONYMOUS_ID
        DRUPAL_AUTHENTICATED_RID: Drupal\user\RoleInterface::AUTHENTICATED_ID
        DRUPAL_USER_TIMEZONE_DEFAULT: Drupal\user\UserInterface::TIMEZONE_DEFAULT
        DRUPAL_USER_TIMEZONE_EMPTY: Drupal\user\UserInterface::TIMEZONE_EMPTY
        DRUPAL_USER_TIMEZONE_SELECT: Drupal\user\UserInterface::TIMEZONE_SELECT
        FILE_CHMOD_DIRECTORY: Drupal\Core\File\FileSystem::CHMOD_DIRECTORY
        FILE_CHMOD_FILE: Drupal\Core\File\FileSystem::CHMOD_FILE
        LOCALE_PLURAL_DELIMITER: Drupal\Core\StringTranslation\PluralTranslatableMarkup::DELIMITER
        MENU_MAX_MENU_NAME_LENGTH_UI: Drupal\Core\Config\Entity\ConfigEntityStorage::MAX_ID_LENGTH
        NODE_NOT_PROMOTED: Drupal\node\NodeInterface::NOT_PROMOTED
        NODE_NOT_PUBLISHED: Drupal\node\NodeInterface::NOT_PUBLISHED
        NODE_NOT_STICKY: Drupal\node\NodeInterface::NOT_STICKY
        NODE_PROMOTED: Drupal\node\NodeInterface::PROMOTED
        NODE_PUBLISHED: Drupal\node\NodeInterface::PUBLISHED
        NODE_STICKY: Drupal\node\NodeInterface::STICKY
        REGIONS_ALL: Drupal\block\BlockRepositoryInterface::REGIONS_ALL
        REGIONS_VISIBLE: Drupal\block\BlockRepositoryInterface::REGIONS_VISIBLE
        RESPONSIVE_IMAGE_EMPTY_IMAGE: Drupal\responsive_image\ResponsiveImageStyleInterface::EMPTY_IMAGE
        RESPONSIVE_IMAGE_ORIGINAL_IMAGE: Drupal\responsive_image\ResponsiveImageStyleInterface::ORIGINAL_IMAGE
        TAXONOMY_HIERARCHY_DISABLED: Drupal\taxonomy\VocabularyInterface::HIERARCHY_DISABLED
        TAXONOMY_HIERARCHY_MULTIPLE: Drupal\taxonomy\VocabularyInterface::HIERARCHY_MULTIPLE
        TAXONOMY_HIERARCHY_SINGLE: Drupal\taxonomy\VocabularyInterface::HIERARCHY_SINGLE
        UPDATE_CURRENT: Drupal\update\UpdateManagerInterface::CURRENT
        UPDATE_FETCH_PENDING: Drupal\update\UpdateManagerInterface::FETCH_PENDING
        UPDATE_NOT_CHECKED: Drupal\update\UpdateManagerInterface::NOT_CHECKED
        UPDATE_NOT_CURRENT: Drupal\update\UpdateManagerInterface::NOT_CURRENT
        UPDATE_NOT_FETCHED: Drupal\update\UpdateManagerInterface::NOT_FETCHED
        UPDATE_NOT_SECURE: Drupal\update\UpdateManagerInterface::NOT_SECURE
        UPDATE_NOT_SUPPORTED: Drupal\update\UpdateManagerInterface::NOT_SUPPORTED
        UPDATE_REVOKED: Drupal\update\UpdateManagerInterface::REVOKED
        UPDATE_UNKNOWN: Drupal\update\UpdateManagerInterface::UNKNOWN
        USERNAME_MAX_LENGTH: Drupal\user\UserInterface::USERNAME_MAX_LENGTH
        USER_REGISTER_ADMINISTRATORS_ONLY: Drupal\user\UserInterface::REGISTER_ADMINISTRATORS_ONLY
        USER_REGISTER_VISITORS: Drupal\user\UserInterface::REGISTER_VISITORS
        USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL: Drupal\user\UserInterface::REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL

# Contains automatic fixes for some deprecations introduced _before_ and in Drupal 8.6.
services:
    Rector\Rector\MethodCall\RenameMethodRector:
        arguments: ['%Rector\Rector\MethodCall\RenameMethodRector%']

    Drupal8Rector\Rector\Deprecation\ConstToClassConstFetchRector:
        arguments: ['%Drupal8Rector\Rector\Deprecation\ConstToClassConstFetchRector%']

    # Do not forget to optimize imports after this rector.
    Drupal8Rector\Rector\Deprecation\UrlGeneratorTraitRector: ~

    Drupal8Rector\Rector\Deprecation\DrupalSetMessageRector: ~
