imports:
    - { resource: "../config/drupal8.yml" }
    - { resource: "../config/drupal86-deprecations.yml" }

parameters:
    autoload_paths:
        - '.drupal/web/autoload.php'
        - '.drupal/web/core/modules'
        - '.drupal/web/modules'
    exclude_paths:
        - '*/tests/*'
        - '*/Tests/*'
    file_extensions:
        - module
