# General ruleset for Drupal 8.
imports:
    - { resource: "./drupal-8.0-deprecations.yml" }
    - { resource: "./drupal-8.5-deprecations.yml" }
    - { resource: "./drupal-8.6-deprecations.yml" }
    - { resource: "./drupal-8.7-deprecations.yml" }

parameters:
    exclude_rectors:

services:
